/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AAndEE extends PE
{
    private PAndE _andE_;

    public AAndEE()
    {
        // Constructor
    }

    public AAndEE(
        @SuppressWarnings("hiding") PAndE _andE_)
    {
        // Constructor
        setAndE(_andE_);

    }

    @Override
    public Object clone()
    {
        return new AAndEE(
            cloneNode(this._andE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndEE(this);
    }

    public PAndE getAndE()
    {
        return this._andE_;
    }

    public void setAndE(PAndE node)
    {
        if(this._andE_ != null)
        {
            this._andE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._andE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._andE_ == child)
        {
            this._andE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._andE_ == oldChild)
        {
            setAndE((PAndE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
