/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AArithLowECompE extends PCompE
{
    private PArithLowE _arithLowE_;

    public AArithLowECompE()
    {
        // Constructor
    }

    public AArithLowECompE(
        @SuppressWarnings("hiding") PArithLowE _arithLowE_)
    {
        // Constructor
        setArithLowE(_arithLowE_);

    }

    @Override
    public Object clone()
    {
        return new AArithLowECompE(
            cloneNode(this._arithLowE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArithLowECompE(this);
    }

    public PArithLowE getArithLowE()
    {
        return this._arithLowE_;
    }

    public void setArithLowE(PArithLowE node)
    {
        if(this._arithLowE_ != null)
        {
            this._arithLowE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arithLowE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arithLowE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arithLowE_ == child)
        {
            this._arithLowE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arithLowE_ == oldChild)
        {
            setArithLowE((PArithLowE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
