/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AArithHighEArithLowE extends PArithLowE
{
    private PArithHighE _arithHighE_;

    public AArithHighEArithLowE()
    {
        // Constructor
    }

    public AArithHighEArithLowE(
        @SuppressWarnings("hiding") PArithHighE _arithHighE_)
    {
        // Constructor
        setArithHighE(_arithHighE_);

    }

    @Override
    public Object clone()
    {
        return new AArithHighEArithLowE(
            cloneNode(this._arithHighE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArithHighEArithLowE(this);
    }

    public PArithHighE getArithHighE()
    {
        return this._arithHighE_;
    }

    public void setArithHighE(PArithHighE node)
    {
        if(this._arithHighE_ != null)
        {
            this._arithHighE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arithHighE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arithHighE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arithHighE_ == child)
        {
            this._arithHighE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arithHighE_ == oldChild)
        {
            setArithHighE((PArithHighE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
