/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADivArithHighE extends PArithHighE
{
    private PArithHighE _arithHighE_;
    private TDiv _div_;
    private PNegE _negE_;

    public ADivArithHighE()
    {
        // Constructor
    }

    public ADivArithHighE(
        @SuppressWarnings("hiding") PArithHighE _arithHighE_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PNegE _negE_)
    {
        // Constructor
        setArithHighE(_arithHighE_);

        setDiv(_div_);

        setNegE(_negE_);

    }

    @Override
    public Object clone()
    {
        return new ADivArithHighE(
            cloneNode(this._arithHighE_),
            cloneNode(this._div_),
            cloneNode(this._negE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivArithHighE(this);
    }

    public PArithHighE getArithHighE()
    {
        return this._arithHighE_;
    }

    public void setArithHighE(PArithHighE node)
    {
        if(this._arithHighE_ != null)
        {
            this._arithHighE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arithHighE_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PNegE getNegE()
    {
        return this._negE_;
    }

    public void setNegE(PNegE node)
    {
        if(this._negE_ != null)
        {
            this._negE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arithHighE_)
            + toString(this._div_)
            + toString(this._negE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arithHighE_ == child)
        {
            this._arithHighE_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._negE_ == child)
        {
            this._negE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arithHighE_ == oldChild)
        {
            setArithHighE((PArithHighE) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._negE_ == oldChild)
        {
            setNegE((PNegE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
