/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AEE extends PE
{
    private PE _e_;
    private TOr _or_;
    private PAndE _andE_;

    public AEE()
    {
        // Constructor
    }

    public AEE(
        @SuppressWarnings("hiding") PE _e_,
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") PAndE _andE_)
    {
        // Constructor
        setE(_e_);

        setOr(_or_);

        setAndE(_andE_);

    }

    @Override
    public Object clone()
    {
        return new AEE(
            cloneNode(this._e_),
            cloneNode(this._or_),
            cloneNode(this._andE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEE(this);
    }

    public PE getE()
    {
        return this._e_;
    }

    public void setE(PE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public PAndE getAndE()
    {
        return this._andE_;
    }

    public void setAndE(PAndE node)
    {
        if(this._andE_ != null)
        {
            this._andE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e_)
            + toString(this._or_)
            + toString(this._andE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._andE_ == child)
        {
            this._andE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e_ == oldChild)
        {
            setE((PE) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._andE_ == oldChild)
        {
            setAndE((PAndE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
