/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AElementParenthE extends PParenthE
{
    private PElement _element_;

    public AElementParenthE()
    {
        // Constructor
    }

    public AElementParenthE(
        @SuppressWarnings("hiding") PElement _element_)
    {
        // Constructor
        setElement(_element_);

    }

    @Override
    public Object clone()
    {
        return new AElementParenthE(
            cloneNode(this._element_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElementParenthE(this);
    }

    public PElement getElement()
    {
        return this._element_;
    }

    public void setElement(PElement node)
    {
        if(this._element_ != null)
        {
            this._element_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._element_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._element_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._element_ == child)
        {
            this._element_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._element_ == oldChild)
        {
            setElement((PElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
