/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AExclamationMarkNegE extends PNegE
{
    private TNot _not_;
    private PParenthE _parenthE_;

    public AExclamationMarkNegE()
    {
        // Constructor
    }

    public AExclamationMarkNegE(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PParenthE _parenthE_)
    {
        // Constructor
        setNot(_not_);

        setParenthE(_parenthE_);

    }

    @Override
    public Object clone()
    {
        return new AExclamationMarkNegE(
            cloneNode(this._not_),
            cloneNode(this._parenthE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExclamationMarkNegE(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PParenthE getParenthE()
    {
        return this._parenthE_;
    }

    public void setParenthE(PParenthE node)
    {
        if(this._parenthE_ != null)
        {
            this._parenthE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenthE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._parenthE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._parenthE_ == child)
        {
            this._parenthE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._parenthE_ == oldChild)
        {
            setParenthE((PParenthE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
