/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMoinsArithLowE extends PArithLowE
{
    private PArithLowE _arithLowE_;
    private TMinus _minus_;
    private PArithHighE _arithHighE_;

    public AMoinsArithLowE()
    {
        // Constructor
    }

    public AMoinsArithLowE(
        @SuppressWarnings("hiding") PArithLowE _arithLowE_,
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PArithHighE _arithHighE_)
    {
        // Constructor
        setArithLowE(_arithLowE_);

        setMinus(_minus_);

        setArithHighE(_arithHighE_);

    }

    @Override
    public Object clone()
    {
        return new AMoinsArithLowE(
            cloneNode(this._arithLowE_),
            cloneNode(this._minus_),
            cloneNode(this._arithHighE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoinsArithLowE(this);
    }

    public PArithLowE getArithLowE()
    {
        return this._arithLowE_;
    }

    public void setArithLowE(PArithLowE node)
    {
        if(this._arithLowE_ != null)
        {
            this._arithLowE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arithLowE_ = node;
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PArithHighE getArithHighE()
    {
        return this._arithHighE_;
    }

    public void setArithHighE(PArithHighE node)
    {
        if(this._arithHighE_ != null)
        {
            this._arithHighE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arithHighE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arithLowE_)
            + toString(this._minus_)
            + toString(this._arithHighE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arithLowE_ == child)
        {
            this._arithLowE_ = null;
            return;
        }

        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._arithHighE_ == child)
        {
            this._arithHighE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arithLowE_ == oldChild)
        {
            setArithLowE((PArithLowE) newChild);
            return;
        }

        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._arithHighE_ == oldChild)
        {
            setArithHighE((PArithHighE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
