/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANumberElement extends PElement
{
    private TNb _nb_;

    public ANumberElement()
    {
        // Constructor
    }

    public ANumberElement(
        @SuppressWarnings("hiding") TNb _nb_)
    {
        // Constructor
        setNb(_nb_);

    }

    @Override
    public Object clone()
    {
        return new ANumberElement(
            cloneNode(this._nb_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumberElement(this);
    }

    public TNb getNb()
    {
        return this._nb_;
    }

    public void setNb(TNb node)
    {
        if(this._nb_ != null)
        {
            this._nb_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nb_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nb_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nb_ == child)
        {
            this._nb_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nb_ == oldChild)
        {
            setNb((TNb) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
