/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AProgProgramme extends PProgramme
{
    private PLdvOptional _ldvOptional_;
    private PLdf _ldf_;

    public AProgProgramme()
    {
        // Constructor
    }

    public AProgProgramme(
        @SuppressWarnings("hiding") PLdvOptional _ldvOptional_,
        @SuppressWarnings("hiding") PLdf _ldf_)
    {
        // Constructor
        setLdvOptional(_ldvOptional_);

        setLdf(_ldf_);

    }

    @Override
    public Object clone()
    {
        return new AProgProgramme(
            cloneNode(this._ldvOptional_),
            cloneNode(this._ldf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgProgramme(this);
    }

    public PLdvOptional getLdvOptional()
    {
        return this._ldvOptional_;
    }

    public void setLdvOptional(PLdvOptional node)
    {
        if(this._ldvOptional_ != null)
        {
            this._ldvOptional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldvOptional_ = node;
    }

    public PLdf getLdf()
    {
        return this._ldf_;
    }

    public void setLdf(PLdf node)
    {
        if(this._ldf_ != null)
        {
            this._ldf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ldvOptional_)
            + toString(this._ldf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ldvOptional_ == child)
        {
            this._ldvOptional_ = null;
            return;
        }

        if(this._ldf_ == child)
        {
            this._ldf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ldvOptional_ == oldChild)
        {
            setLdvOptional((PLdvOptional) newChild);
            return;
        }

        if(this._ldf_ == oldChild)
        {
            setLdf((PLdf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
