/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.parser;

import sc.lexer.*;
import sc.node.*;
import sc.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgramme node1 = (PProgramme) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AProgProgramme */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AListFuncLdf */
            {
                ArrayList<Object> list = new1();
                push(goTo(1), list, false);
            }
            break;
            case 2: /* reduce AEpsLdf */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce ADefFuncDf */
            {
                ArrayList<Object> list = new3();
                push(goTo(2), list, false);
            }
            break;
            case 4: /* reduce AOptListVarLdvOptional */
            {
                ArrayList<Object> list = new4();
                push(goTo(3), list, false);
            }
            break;
            case 5: /* reduce AEpsLdvOptional */
            {
                ArrayList<Object> list = new5();
                push(goTo(3), list, false);
            }
            break;
            case 6: /* reduce AListVarLdv */
            {
                ArrayList<Object> list = new6();
                push(goTo(4), list, false);
            }
            break;
            case 7: /* reduce AEpsLdv */
            {
                ArrayList<Object> list = new7();
                push(goTo(4), list, false);
            }
            break;
            case 8: /* reduce AListVarAfterCommaLdvBis */
            {
                ArrayList<Object> list = new8();
                push(goTo(5), list, false);
            }
            break;
            case 9: /* reduce AEpsLdvBis */
            {
                ArrayList<Object> list = new9();
                push(goTo(5), list, false);
            }
            break;
            case 10: /* reduce ADefVarDv */
            {
                ArrayList<Object> list = new10();
                push(goTo(6), list, false);
            }
            break;
            case 11: /* reduce ADefVarArrayDv */
            {
                ArrayList<Object> list = new11();
                push(goTo(6), list, false);
            }
            break;
            case 12: /* reduce ADefVarAffectationDv */
            {
                ArrayList<Object> list = new12();
                push(goTo(6), list, false);
            }
            break;
            case 13: /* reduce ABlocInstBi */
            {
                ArrayList<Object> list = new13();
                push(goTo(7), list, false);
            }
            break;
            case 14: /* reduce AListInstLi */
            {
                ArrayList<Object> list = new14();
                push(goTo(8), list, false);
            }
            break;
            case 15: /* reduce AListInstNextIBis */
            {
                ArrayList<Object> list = new15();
                push(goTo(9), list, false);
            }
            break;
            case 16: /* reduce AEpsIBis */
            {
                ArrayList<Object> list = new16();
                push(goTo(9), list, false);
            }
            break;
            case 17: /* reduce AAffectI */
            {
                ArrayList<Object> list = new17();
                push(goTo(10), list, false);
            }
            break;
            case 18: /* reduce AAffectInArrayI */
            {
                ArrayList<Object> list = new18();
                push(goTo(10), list, false);
            }
            break;
            case 19: /* reduce AIfI */
            {
                ArrayList<Object> list = new19();
                push(goTo(10), list, false);
            }
            break;
            case 20: /* reduce AWhileI */
            {
                ArrayList<Object> list = new20();
                push(goTo(10), list, false);
            }
            break;
            case 21: /* reduce ARetI */
            {
                ArrayList<Object> list = new21();
                push(goTo(10), list, false);
            }
            break;
            case 22: /* reduce AFuncCallI */
            {
                ArrayList<Object> list = new22();
                push(goTo(10), list, false);
            }
            break;
            case 23: /* reduce AWriteI */
            {
                ArrayList<Object> list = new23();
                push(goTo(10), list, false);
            }
            break;
            case 24: /* reduce AElseElseBlock */
            {
                ArrayList<Object> list = new24();
                push(goTo(11), list, false);
            }
            break;
            case 25: /* reduce AEpsElseBlock */
            {
                ArrayList<Object> list = new25();
                push(goTo(11), list, false);
            }
            break;
            case 26: /* reduce AEE */
            {
                ArrayList<Object> list = new26();
                push(goTo(12), list, false);
            }
            break;
            case 27: /* reduce AAndEE */
            {
                ArrayList<Object> list = new27();
                push(goTo(12), list, false);
            }
            break;
            case 28: /* reduce AAndEAndE */
            {
                ArrayList<Object> list = new28();
                push(goTo(13), list, false);
            }
            break;
            case 29: /* reduce ACompEAndE */
            {
                ArrayList<Object> list = new29();
                push(goTo(13), list, false);
            }
            break;
            case 30: /* reduce AEqualCompE */
            {
                ArrayList<Object> list = new30();
                push(goTo(14), list, false);
            }
            break;
            case 31: /* reduce ALowerThanCompE */
            {
                ArrayList<Object> list = new31();
                push(goTo(14), list, false);
            }
            break;
            case 32: /* reduce AArithLowECompE */
            {
                ArrayList<Object> list = new32();
                push(goTo(14), list, false);
            }
            break;
            case 33: /* reduce APlusArithLowE */
            {
                ArrayList<Object> list = new33();
                push(goTo(15), list, false);
            }
            break;
            case 34: /* reduce AMoinsArithLowE */
            {
                ArrayList<Object> list = new34();
                push(goTo(15), list, false);
            }
            break;
            case 35: /* reduce AArithHighEArithLowE */
            {
                ArrayList<Object> list = new35();
                push(goTo(15), list, false);
            }
            break;
            case 36: /* reduce AMultArithHighE */
            {
                ArrayList<Object> list = new36();
                push(goTo(16), list, false);
            }
            break;
            case 37: /* reduce ADivArithHighE */
            {
                ArrayList<Object> list = new37();
                push(goTo(16), list, false);
            }
            break;
            case 38: /* reduce ANegEArithHighE */
            {
                ArrayList<Object> list = new38();
                push(goTo(16), list, false);
            }
            break;
            case 39: /* reduce ANotNegE */
            {
                ArrayList<Object> list = new39();
                push(goTo(17), list, false);
            }
            break;
            case 40: /* reduce AParenthENegE */
            {
                ArrayList<Object> list = new40();
                push(goTo(17), list, false);
            }
            break;
            case 41: /* reduce AParenthParenthE */
            {
                ArrayList<Object> list = new41();
                push(goTo(18), list, false);
            }
            break;
            case 42: /* reduce AElementParenthE */
            {
                ArrayList<Object> list = new42();
                push(goTo(18), list, false);
            }
            break;
            case 43: /* reduce ANumberElement */
            {
                ArrayList<Object> list = new43();
                push(goTo(19), list, false);
            }
            break;
            case 44: /* reduce AVariableElement */
            {
                ArrayList<Object> list = new44();
                push(goTo(19), list, false);
            }
            break;
            case 45: /* reduce AArrayElementElement */
            {
                ArrayList<Object> list = new45();
                push(goTo(19), list, false);
            }
            break;
            case 46: /* reduce AReadElement */
            {
                ArrayList<Object> list = new46();
                push(goTo(19), list, false);
            }
            break;
            case 47: /* reduce AFuncCallElement */
            {
                ArrayList<Object> list = new47();
                push(goTo(19), list, false);
            }
            break;
            case 48: /* reduce ADefFuncCallAppFunction */
            {
                ArrayList<Object> list = new48();
                push(goTo(20), list, false);
            }
            break;
            case 49: /* reduce AListExpLe */
            {
                ArrayList<Object> list = new49();
                push(goTo(21), list, false);
            }
            break;
            case 50: /* reduce AEpsLe */
            {
                ArrayList<Object> list = new50();
                push(goTo(21), list, false);
            }
            break;
            case 51: /* reduce AExpAfterCommaEBis */
            {
                ArrayList<Object> list = new51();
                push(goTo(22), list, false);
            }
            break;
            case 52: /* reduce AEpsEBis */
            {
                ArrayList<Object> list = new52();
                push(goTo(22), list, false);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AProgProgramme */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgramme pprogrammeNode1;
        {
            // Block
        PLdvOptional pldvoptionalNode2;
        PLdf pldfNode3;
        pldvoptionalNode2 = (PLdvOptional)nodeArrayList1.get(0);
        pldfNode3 = (PLdf)nodeArrayList2.get(0);

        pprogrammeNode1 = new AProgProgramme(pldvoptionalNode2, pldfNode3);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AListFuncLdf */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLdf pldfNode1;
        {
            // Block
        PDf pdfNode2;
        PLdf pldfNode3;
        pdfNode2 = (PDf)nodeArrayList1.get(0);
        pldfNode3 = (PLdf)nodeArrayList2.get(0);

        pldfNode1 = new AListFuncLdf(pdfNode2, pldfNode3);
        }
	nodeList.add(pldfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AEpsLdf */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLdf pldfNode1;
        {
            // Block

        pldfNode1 = new AEpsLdf();
        }
	nodeList.add(pldfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce ADefFuncDf */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDf pdfNode1;
        {
            // Block
        TId tidNode2;
        TPo tpoNode3;
        PLdv pldvNode4;
        TPf tpfNode5;
        PLdvOptional pldvoptionalNode6;
        PBi pbiNode7;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        pldvNode4 = (PLdv)nodeArrayList3.get(0);
        tpfNode5 = (TPf)nodeArrayList4.get(0);
        pldvoptionalNode6 = (PLdvOptional)nodeArrayList5.get(0);
        pbiNode7 = (PBi)nodeArrayList6.get(0);

        pdfNode1 = new ADefFuncDf(tidNode2, tpoNode3, pldvNode4, tpfNode5, pldvoptionalNode6, pbiNode7);
        }
	nodeList.add(pdfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AOptListVarLdvOptional */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLdvOptional pldvoptionalNode1;
        {
            // Block
        PLdv pldvNode2;
        TSemicolon tsemicolonNode3;
        pldvNode2 = (PLdv)nodeArrayList1.get(0);
        tsemicolonNode3 = (TSemicolon)nodeArrayList2.get(0);

        pldvoptionalNode1 = new AOptListVarLdvOptional(pldvNode2, tsemicolonNode3);
        }
	nodeList.add(pldvoptionalNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce AEpsLdvOptional */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLdvOptional pldvoptionalNode1;
        {
            // Block

        pldvoptionalNode1 = new AEpsLdvOptional();
        }
	nodeList.add(pldvoptionalNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce AListVarLdv */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLdv pldvNode1;
        {
            // Block
        PDv pdvNode2;
        PLdvBis pldvbisNode3;
        pdvNode2 = (PDv)nodeArrayList1.get(0);
        pldvbisNode3 = (PLdvBis)nodeArrayList2.get(0);

        pldvNode1 = new AListVarLdv(pdvNode2, pldvbisNode3);
        }
	nodeList.add(pldvNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AEpsLdv */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLdv pldvNode1;
        {
            // Block

        pldvNode1 = new AEpsLdv();
        }
	nodeList.add(pldvNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce AListVarAfterCommaLdvBis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLdvBis pldvbisNode1;
        {
            // Block
        TComma tcommaNode2;
        PDv pdvNode3;
        PLdvBis pldvbisNode4;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        pdvNode3 = (PDv)nodeArrayList2.get(0);
        pldvbisNode4 = (PLdvBis)nodeArrayList3.get(0);

        pldvbisNode1 = new AListVarAfterCommaLdvBis(tcommaNode2, pdvNode3, pldvbisNode4);
        }
	nodeList.add(pldvbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AEpsLdvBis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLdvBis pldvbisNode1;
        {
            // Block

        pldvbisNode1 = new AEpsLdvBis();
        }
	nodeList.add(pldvbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce ADefVarDv */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDv pdvNode1;
        {
            // Block
        TVarType tvartypeNode2;
        TId tidNode3;
        tvartypeNode2 = (TVarType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pdvNode1 = new ADefVarDv(tvartypeNode2, tidNode3);
        }
	nodeList.add(pdvNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce ADefVarArrayDv */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDv pdvNode1;
        {
            // Block
        TVarType tvartypeNode2;
        TId tidNode3;
        TCo tcoNode4;
        TNb tnbNode5;
        TCf tcfNode6;
        tvartypeNode2 = (TVarType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tcoNode4 = (TCo)nodeArrayList3.get(0);
        tnbNode5 = (TNb)nodeArrayList4.get(0);
        tcfNode6 = (TCf)nodeArrayList5.get(0);

        pdvNode1 = new ADefVarArrayDv(tvartypeNode2, tidNode3, tcoNode4, tnbNode5, tcfNode6);
        }
	nodeList.add(pdvNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce ADefVarAffectationDv */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDv pdvNode1;
        {
            // Block
        TVarType tvartypeNode2;
        TId tidNode3;
        TEqual tequalNode4;
        PE peNode5;
        tvartypeNode2 = (TVarType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tequalNode4 = (TEqual)nodeArrayList3.get(0);
        peNode5 = (PE)nodeArrayList4.get(0);

        pdvNode1 = new ADefVarAffectationDv(tvartypeNode2, tidNode3, tequalNode4, peNode5);
        }
	nodeList.add(pdvNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce ABlocInstBi */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PBi pbiNode1;
        {
            // Block
        TAo taoNode2;
        PLi pliNode3;
        TAf tafNode4;
        taoNode2 = (TAo)nodeArrayList1.get(0);
        pliNode3 = (PLi)nodeArrayList2.get(0);
        tafNode4 = (TAf)nodeArrayList3.get(0);

        pbiNode1 = new ABlocInstBi(taoNode2, pliNode3, tafNode4);
        }
	nodeList.add(pbiNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce AListInstLi */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLi pliNode1;
        {
            // Block
        PI piNode2;
        PIBis pibisNode3;
        piNode2 = (PI)nodeArrayList1.get(0);
        pibisNode3 = (PIBis)nodeArrayList2.get(0);

        pliNode1 = new AListInstLi(piNode2, pibisNode3);
        }
	nodeList.add(pliNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce AListInstNextIBis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIBis pibisNode1;
        {
            // Block
        PI piNode2;
        PIBis pibisNode3;
        piNode2 = (PI)nodeArrayList1.get(0);
        pibisNode3 = (PIBis)nodeArrayList2.get(0);

        pibisNode1 = new AListInstNextIBis(piNode2, pibisNode3);
        }
	nodeList.add(pibisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce AEpsIBis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PIBis pibisNode1;
        {
            // Block

        pibisNode1 = new AEpsIBis();
        }
	nodeList.add(pibisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce AAffectI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TId tidNode2;
        TEqual tequalNode3;
        PE peNode4;
        TSemicolon tsemicolonNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tequalNode3 = (TEqual)nodeArrayList2.get(0);
        peNode4 = (PE)nodeArrayList3.get(0);
        tsemicolonNode5 = (TSemicolon)nodeArrayList4.get(0);

        piNode1 = new AAffectI(tidNode2, tequalNode3, peNode4, tsemicolonNode5);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce AAffectInArrayI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TId tidNode2;
        TCo tcoNode3;
        TNb tnbNode4;
        TCf tcfNode5;
        TEqual tequalNode6;
        PE peNode7;
        TSemicolon tsemicolonNode8;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tcoNode3 = (TCo)nodeArrayList2.get(0);
        tnbNode4 = (TNb)nodeArrayList3.get(0);
        tcfNode5 = (TCf)nodeArrayList4.get(0);
        tequalNode6 = (TEqual)nodeArrayList5.get(0);
        peNode7 = (PE)nodeArrayList6.get(0);
        tsemicolonNode8 = (TSemicolon)nodeArrayList7.get(0);

        piNode1 = new AAffectInArrayI(tidNode2, tcoNode3, tnbNode4, tcfNode5, tequalNode6, peNode7, tsemicolonNode8);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce AIfI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TIf tifNode2;
        PE peNode3;
        TThen tthenNode4;
        PBi pbiNode5;
        PElseBlock pelseblockNode6;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        peNode3 = (PE)nodeArrayList2.get(0);
        tthenNode4 = (TThen)nodeArrayList3.get(0);
        pbiNode5 = (PBi)nodeArrayList4.get(0);
        pelseblockNode6 = (PElseBlock)nodeArrayList5.get(0);

        piNode1 = new AIfI(tifNode2, peNode3, tthenNode4, pbiNode5, pelseblockNode6);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce AWhileI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TWhile twhileNode2;
        PE peNode3;
        TDo tdoNode4;
        PBi pbiNode5;
        twhileNode2 = (TWhile)nodeArrayList1.get(0);
        peNode3 = (PE)nodeArrayList2.get(0);
        tdoNode4 = (TDo)nodeArrayList3.get(0);
        pbiNode5 = (PBi)nodeArrayList4.get(0);

        piNode1 = new AWhileI(twhileNode2, peNode3, tdoNode4, pbiNode5);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce ARetI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TReturn treturnNode2;
        PE peNode3;
        TSemicolon tsemicolonNode4;
        treturnNode2 = (TReturn)nodeArrayList1.get(0);
        peNode3 = (PE)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        piNode1 = new ARetI(treturnNode2, peNode3, tsemicolonNode4);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AFuncCallI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TId tidNode2;
        TPo tpoNode3;
        PLe pleNode4;
        TPf tpfNode5;
        TSemicolon tsemicolonNode6;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        pleNode4 = (PLe)nodeArrayList3.get(0);
        tpfNode5 = (TPf)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        piNode1 = new AFuncCallI(tidNode2, tpoNode3, pleNode4, tpfNode5, tsemicolonNode6);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce AWriteI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TWrite twriteNode2;
        TPo tpoNode3;
        PE peNode4;
        TPf tpfNode5;
        TSemicolon tsemicolonNode6;
        twriteNode2 = (TWrite)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        peNode4 = (PE)nodeArrayList3.get(0);
        tpfNode5 = (TPf)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        piNode1 = new AWriteI(twriteNode2, tpoNode3, peNode4, tpfNode5, tsemicolonNode6);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce AElseElseBlock */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElseBlock pelseblockNode1;
        {
            // Block
        TElse telseNode2;
        PBi pbiNode3;
        telseNode2 = (TElse)nodeArrayList1.get(0);
        pbiNode3 = (PBi)nodeArrayList2.get(0);

        pelseblockNode1 = new AElseElseBlock(telseNode2, pbiNode3);
        }
	nodeList.add(pelseblockNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce AEpsElseBlock */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PElseBlock pelseblockNode1;
        {
            // Block

        pelseblockNode1 = new AEpsElseBlock();
        }
	nodeList.add(pelseblockNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce AEE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PE peNode1;
        {
            // Block
        PE peNode2;
        TOr torNode3;
        PAndE pandeNode4;
        peNode2 = (PE)nodeArrayList1.get(0);
        torNode3 = (TOr)nodeArrayList2.get(0);
        pandeNode4 = (PAndE)nodeArrayList3.get(0);

        peNode1 = new AEE(peNode2, torNode3, pandeNode4);
        }
	nodeList.add(peNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AAndEE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PE peNode1;
        {
            // Block
        PAndE pandeNode2;
        pandeNode2 = (PAndE)nodeArrayList1.get(0);

        peNode1 = new AAndEE(pandeNode2);
        }
	nodeList.add(peNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce AAndEAndE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAndE pandeNode1;
        {
            // Block
        PAndE pandeNode2;
        TAnd tandNode3;
        PCompE pcompeNode4;
        pandeNode2 = (PAndE)nodeArrayList1.get(0);
        tandNode3 = (TAnd)nodeArrayList2.get(0);
        pcompeNode4 = (PCompE)nodeArrayList3.get(0);

        pandeNode1 = new AAndEAndE(pandeNode2, tandNode3, pcompeNode4);
        }
	nodeList.add(pandeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce ACompEAndE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAndE pandeNode1;
        {
            // Block
        PCompE pcompeNode2;
        pcompeNode2 = (PCompE)nodeArrayList1.get(0);

        pandeNode1 = new ACompEAndE(pcompeNode2);
        }
	nodeList.add(pandeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce AEqualCompE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCompE pcompeNode1;
        {
            // Block
        PCompE pcompeNode2;
        TEqual tequalNode3;
        PArithLowE parithloweNode4;
        pcompeNode2 = (PCompE)nodeArrayList1.get(0);
        tequalNode3 = (TEqual)nodeArrayList2.get(0);
        parithloweNode4 = (PArithLowE)nodeArrayList3.get(0);

        pcompeNode1 = new AEqualCompE(pcompeNode2, tequalNode3, parithloweNode4);
        }
	nodeList.add(pcompeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce ALowerThanCompE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCompE pcompeNode1;
        {
            // Block
        PCompE pcompeNode2;
        TLowerThan tlowerthanNode3;
        PArithLowE parithloweNode4;
        pcompeNode2 = (PCompE)nodeArrayList1.get(0);
        tlowerthanNode3 = (TLowerThan)nodeArrayList2.get(0);
        parithloweNode4 = (PArithLowE)nodeArrayList3.get(0);

        pcompeNode1 = new ALowerThanCompE(pcompeNode2, tlowerthanNode3, parithloweNode4);
        }
	nodeList.add(pcompeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce AArithLowECompE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCompE pcompeNode1;
        {
            // Block
        PArithLowE parithloweNode2;
        parithloweNode2 = (PArithLowE)nodeArrayList1.get(0);

        pcompeNode1 = new AArithLowECompE(parithloweNode2);
        }
	nodeList.add(pcompeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce APlusArithLowE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArithLowE parithloweNode1;
        {
            // Block
        PArithLowE parithloweNode2;
        TPlus tplusNode3;
        PArithHighE parithhigheNode4;
        parithloweNode2 = (PArithLowE)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        parithhigheNode4 = (PArithHighE)nodeArrayList3.get(0);

        parithloweNode1 = new APlusArithLowE(parithloweNode2, tplusNode3, parithhigheNode4);
        }
	nodeList.add(parithloweNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AMoinsArithLowE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArithLowE parithloweNode1;
        {
            // Block
        PArithLowE parithloweNode2;
        TMinus tminusNode3;
        PArithHighE parithhigheNode4;
        parithloweNode2 = (PArithLowE)nodeArrayList1.get(0);
        tminusNode3 = (TMinus)nodeArrayList2.get(0);
        parithhigheNode4 = (PArithHighE)nodeArrayList3.get(0);

        parithloweNode1 = new AMoinsArithLowE(parithloweNode2, tminusNode3, parithhigheNode4);
        }
	nodeList.add(parithloweNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AArithHighEArithLowE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArithLowE parithloweNode1;
        {
            // Block
        PArithHighE parithhigheNode2;
        parithhigheNode2 = (PArithHighE)nodeArrayList1.get(0);

        parithloweNode1 = new AArithHighEArithLowE(parithhigheNode2);
        }
	nodeList.add(parithloweNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce AMultArithHighE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArithHighE parithhigheNode1;
        {
            // Block
        PArithHighE parithhigheNode2;
        TMult tmultNode3;
        PNegE pnegeNode4;
        parithhigheNode2 = (PArithHighE)nodeArrayList1.get(0);
        tmultNode3 = (TMult)nodeArrayList2.get(0);
        pnegeNode4 = (PNegE)nodeArrayList3.get(0);

        parithhigheNode1 = new AMultArithHighE(parithhigheNode2, tmultNode3, pnegeNode4);
        }
	nodeList.add(parithhigheNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce ADivArithHighE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArithHighE parithhigheNode1;
        {
            // Block
        PArithHighE parithhigheNode2;
        TDiv tdivNode3;
        PNegE pnegeNode4;
        parithhigheNode2 = (PArithHighE)nodeArrayList1.get(0);
        tdivNode3 = (TDiv)nodeArrayList2.get(0);
        pnegeNode4 = (PNegE)nodeArrayList3.get(0);

        parithhigheNode1 = new ADivArithHighE(parithhigheNode2, tdivNode3, pnegeNode4);
        }
	nodeList.add(parithhigheNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce ANegEArithHighE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArithHighE parithhigheNode1;
        {
            // Block
        PNegE pnegeNode2;
        pnegeNode2 = (PNegE)nodeArrayList1.get(0);

        parithhigheNode1 = new ANegEArithHighE(pnegeNode2);
        }
	nodeList.add(parithhigheNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce ANotNegE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PNegE pnegeNode1;
        {
            // Block
        TNot tnotNode2;
        PParenthE pparentheNode3;
        tnotNode2 = (TNot)nodeArrayList1.get(0);
        pparentheNode3 = (PParenthE)nodeArrayList2.get(0);

        pnegeNode1 = new ANotNegE(tnotNode2, pparentheNode3);
        }
	nodeList.add(pnegeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce AParenthENegE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PNegE pnegeNode1;
        {
            // Block
        PParenthE pparentheNode2;
        pparentheNode2 = (PParenthE)nodeArrayList1.get(0);

        pnegeNode1 = new AParenthENegE(pparentheNode2);
        }
	nodeList.add(pnegeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce AParenthParenthE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParenthE pparentheNode1;
        {
            // Block
        TPo tpoNode2;
        PE peNode3;
        TPf tpfNode4;
        tpoNode2 = (TPo)nodeArrayList1.get(0);
        peNode3 = (PE)nodeArrayList2.get(0);
        tpfNode4 = (TPf)nodeArrayList3.get(0);

        pparentheNode1 = new AParenthParenthE(tpoNode2, peNode3, tpfNode4);
        }
	nodeList.add(pparentheNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce AElementParenthE */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParenthE pparentheNode1;
        {
            // Block
        PElement pelementNode2;
        pelementNode2 = (PElement)nodeArrayList1.get(0);

        pparentheNode1 = new AElementParenthE(pelementNode2);
        }
	nodeList.add(pparentheNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce ANumberElement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElement pelementNode1;
        {
            // Block
        TNb tnbNode2;
        tnbNode2 = (TNb)nodeArrayList1.get(0);

        pelementNode1 = new ANumberElement(tnbNode2);
        }
	nodeList.add(pelementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce AVariableElement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElement pelementNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pelementNode1 = new AVariableElement(tidNode2);
        }
	nodeList.add(pelementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce AArrayElementElement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElement pelementNode1;
        {
            // Block
        TId tidNode2;
        TCo tcoNode3;
        PE peNode4;
        TCf tcfNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tcoNode3 = (TCo)nodeArrayList2.get(0);
        peNode4 = (PE)nodeArrayList3.get(0);
        tcfNode5 = (TCf)nodeArrayList4.get(0);

        pelementNode1 = new AArrayElementElement(tidNode2, tcoNode3, peNode4, tcfNode5);
        }
	nodeList.add(pelementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce AReadElement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElement pelementNode1;
        {
            // Block
        TRead treadNode2;
        TPo tpoNode3;
        TPf tpfNode4;
        treadNode2 = (TRead)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        tpfNode4 = (TPf)nodeArrayList3.get(0);

        pelementNode1 = new AReadElement(treadNode2, tpoNode3, tpfNode4);
        }
	nodeList.add(pelementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce AFuncCallElement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElement pelementNode1;
        {
            // Block
        PAppFunction pappfunctionNode2;
        pappfunctionNode2 = (PAppFunction)nodeArrayList1.get(0);

        pelementNode1 = new AFuncCallElement(pappfunctionNode2);
        }
	nodeList.add(pelementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce ADefFuncCallAppFunction */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAppFunction pappfunctionNode1;
        {
            // Block
        TId tidNode2;
        TPo tpoNode3;
        PLe pleNode4;
        TPf tpfNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        pleNode4 = (PLe)nodeArrayList3.get(0);
        tpfNode5 = (TPf)nodeArrayList4.get(0);

        pappfunctionNode1 = new ADefFuncCallAppFunction(tidNode2, tpoNode3, pleNode4, tpfNode5);
        }
	nodeList.add(pappfunctionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce AListExpLe */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLe pleNode1;
        {
            // Block
        PE peNode2;
        PEBis pebisNode3;
        peNode2 = (PE)nodeArrayList1.get(0);
        pebisNode3 = (PEBis)nodeArrayList2.get(0);

        pleNode1 = new AListExpLe(peNode2, pebisNode3);
        }
	nodeList.add(pleNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce AEpsLe */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLe pleNode1;
        {
            // Block

        pleNode1 = new AEpsLe();
        }
	nodeList.add(pleNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new51() /* reduce AExpAfterCommaEBis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PEBis pebisNode1;
        {
            // Block
        TComma tcommaNode2;
        PE peNode3;
        PEBis pebisNode4;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        peNode3 = (PE)nodeArrayList2.get(0);
        pebisNode4 = (PEBis)nodeArrayList3.get(0);

        pebisNode1 = new AExpAfterCommaEBis(tcommaNode2, peNode3, pebisNode4);
        }
	nodeList.add(pebisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new52() /* reduce AEpsEBis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PEBis pebisNode1;
        {
            // Block

        pebisNode1 = new AEpsEBis();
        }
	nodeList.add(pebisNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 5}, {8, REDUCE, 7}, {18, SHIFT, 1}, },
			{{-1, ERROR, 1}, {27, SHIFT, 6}, },
			{{-1, ERROR, 2}, {28, ACCEPT, -1}, },
			{{-1, REDUCE, 2}, {27, SHIFT, 7}, },
			{{-1, ERROR, 4}, {8, SHIFT, 10}, },
			{{-1, REDUCE, 9}, {7, SHIFT, 11}, },
			{{-1, REDUCE, 10}, {3, SHIFT, 13}, {13, SHIFT, 14}, },
			{{-1, ERROR, 7}, {1, SHIFT, 15}, },
			{{-1, REDUCE, 0}, },
			{{-1, REDUCE, 2}, {27, SHIFT, 7}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 11}, {18, SHIFT, 1}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 13}, {0, SHIFT, 18}, },
			{{-1, ERROR, 14}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, REDUCE, 7}, {18, SHIFT, 1}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 9}, {7, SHIFT, 11}, },
			{{-1, ERROR, 18}, {4, SHIFT, 35}, },
			{{-1, REDUCE, 43}, },
			{{-1, ERROR, 20}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 21}, {0, SHIFT, 19}, {1, SHIFT, 20}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 22}, {1, SHIFT, 38}, },
			{{-1, REDUCE, 44}, {1, SHIFT, 39}, {3, SHIFT, 40}, },
			{{-1, REDUCE, 12}, {16, SHIFT, 41}, },
			{{-1, REDUCE, 27}, {15, SHIFT, 42}, },
			{{-1, REDUCE, 29}, {13, SHIFT, 43}, {17, SHIFT, 44}, },
			{{-1, REDUCE, 32}, {9, SHIFT, 45}, {10, SHIFT, 46}, },
			{{-1, REDUCE, 35}, {11, SHIFT, 47}, {12, SHIFT, 48}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 47}, },
			{{-1, ERROR, 33}, {2, SHIFT, 49}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 36}, {2, SHIFT, 50}, {16, SHIFT, 41}, },
			{{-1, REDUCE, 39}, },
			{{-1, ERROR, 38}, {2, SHIFT, 51}, },
			{{-1, REDUCE, 50}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 40}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 41}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 42}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 43}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 44}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 45}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 46}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 47}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 48}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, REDUCE, 5}, {8, REDUCE, 7}, {18, SHIFT, 1}, },
			{{-1, REDUCE, 41}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 52}, {7, SHIFT, 64}, {16, SHIFT, 41}, },
			{{-1, ERROR, 53}, {2, SHIFT, 66}, },
			{{-1, ERROR, 54}, {4, SHIFT, 67}, {16, SHIFT, 41}, },
			{{-1, REDUCE, 26}, {15, SHIFT, 42}, },
			{{-1, REDUCE, 28}, {13, SHIFT, 43}, {17, SHIFT, 44}, },
			{{-1, REDUCE, 30}, {9, SHIFT, 45}, {10, SHIFT, 46}, },
			{{-1, REDUCE, 31}, {9, SHIFT, 45}, {10, SHIFT, 46}, },
			{{-1, REDUCE, 33}, {11, SHIFT, 47}, {12, SHIFT, 48}, },
			{{-1, REDUCE, 34}, {11, SHIFT, 47}, {12, SHIFT, 48}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 37}, },
			{{-1, ERROR, 63}, {5, SHIFT, 68}, },
			{{-1, ERROR, 64}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 45}, },
			{{-1, ERROR, 68}, {19, SHIFT, 71}, {22, SHIFT, 72}, {25, SHIFT, 73}, {26, SHIFT, 74}, {27, SHIFT, 75}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 52}, {7, SHIFT, 64}, {16, SHIFT, 41}, },
			{{-1, ERROR, 71}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 72}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 73}, {1, SHIFT, 81}, },
			{{-1, ERROR, 74}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 75}, {1, SHIFT, 83}, {3, SHIFT, 84}, {13, SHIFT, 85}, },
			{{-1, ERROR, 76}, {6, SHIFT, 86}, },
			{{-1, REDUCE, 16}, {19, SHIFT, 71}, {22, SHIFT, 72}, {25, SHIFT, 73}, {26, SHIFT, 74}, {27, SHIFT, 75}, },
			{{-1, REDUCE, 51}, },
			{{-1, ERROR, 79}, {16, SHIFT, 41}, {20, SHIFT, 89}, },
			{{-1, ERROR, 80}, {16, SHIFT, 41}, {23, SHIFT, 90}, },
			{{-1, ERROR, 81}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 82}, {8, SHIFT, 92}, {16, SHIFT, 41}, },
			{{-1, REDUCE, 50}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, ERROR, 84}, {0, SHIFT, 94}, },
			{{-1, ERROR, 85}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 16}, {19, SHIFT, 71}, {22, SHIFT, 72}, {25, SHIFT, 73}, {26, SHIFT, 74}, {27, SHIFT, 75}, },
			{{-1, ERROR, 89}, {5, SHIFT, 68}, },
			{{-1, ERROR, 90}, {5, SHIFT, 68}, },
			{{-1, ERROR, 91}, {2, SHIFT, 99}, {16, SHIFT, 41}, },
			{{-1, REDUCE, 21}, },
			{{-1, ERROR, 93}, {2, SHIFT, 100}, },
			{{-1, ERROR, 94}, {4, SHIFT, 101}, },
			{{-1, ERROR, 95}, {8, SHIFT, 102}, {16, SHIFT, 41}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 25}, {21, SHIFT, 103}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 99}, {8, SHIFT, 105}, },
			{{-1, ERROR, 100}, {8, SHIFT, 106}, },
			{{-1, ERROR, 101}, {13, SHIFT, 107}, },
			{{-1, REDUCE, 17}, },
			{{-1, ERROR, 103}, {5, SHIFT, 68}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 22}, },
			{{-1, ERROR, 107}, {0, SHIFT, 19}, {1, SHIFT, 20}, {14, SHIFT, 21}, {24, SHIFT, 22}, {27, SHIFT, 23}, },
			{{-1, REDUCE, 24}, },
			{{-1, ERROR, 109}, {8, SHIFT, 110}, {16, SHIFT, 41}, },
			{{-1, REDUCE, 18}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 8}, {9, 16}, },
			{{-1, 9}, },
			{{-1, 3}, {49, 63}, },
			{{-1, 4}, {15, 33}, },
			{{-1, 12}, {17, 34}, },
			{{-1, 5}, {11, 17}, },
			{{-1, 69}, {89, 97}, {90, 98}, {103, 108}, },
			{{-1, 76}, },
			{{-1, 87}, {88, 96}, },
			{{-1, 88}, {68, 77}, },
			{{-1, 104}, },
			{{-1, 52}, {14, 24}, {20, 36}, {40, 54}, {64, 70}, {71, 79}, {72, 80}, {74, 82}, {81, 91}, {85, 95}, {107, 109}, },
			{{-1, 25}, {41, 55}, },
			{{-1, 26}, {42, 56}, },
			{{-1, 27}, {43, 57}, {44, 58}, },
			{{-1, 28}, {45, 59}, {46, 60}, },
			{{-1, 29}, {47, 61}, {48, 62}, },
			{{-1, 30}, {21, 37}, },
			{{-1, 31}, },
			{{-1, 32}, },
			{{-1, 53}, {83, 93}, },
			{{-1, 65}, {70, 78}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: ';', 'entier', id, EOF",
			"expecting: id",
			"expecting: EOF",
			"expecting: id, EOF",
			"expecting: ';'",
			"expecting: ')', ',', ';'",
			"expecting: ')', '[', ',', ';', '='",
			"expecting: '('",
			"expecting: '{', id, EOF",
			"expecting: 'entier'",
			"expecting: ')', ';'",
			"expecting: nb",
			"expecting: nb, '(', '!', 'lire', id",
			"expecting: ')', 'entier'",
			"expecting: ']'",
			"expecting: ')', ']', ',', ';', '+', '-', '*', '/', '=', '&', '|', '<', 'alors', 'faire'",
			"expecting: nb, '(', 'lire', id",
			"expecting: '(', ')', '[', ']', ',', ';', '+', '-', '*', '/', '=', '&', '|', '<', 'alors', 'faire'",
			"expecting: ')', ',', ';', '|'",
			"expecting: ')', ']', ',', ';', '&', '|', 'alors', 'faire'",
			"expecting: ')', ']', ',', ';', '=', '&', '|', '<', 'alors', 'faire'",
			"expecting: ')', ']', ',', ';', '+', '-', '=', '&', '|', '<', 'alors', 'faire'",
			"expecting: ')'",
			"expecting: ')', '|'",
			"expecting: nb, '(', ')', '!', 'lire', id",
			"expecting: '{', ';', 'entier'",
			"expecting: ')', ',', '|'",
			"expecting: ']', '|'",
			"expecting: '{'",
			"expecting: 'si', 'tantque', 'ecrire', 'retour', id",
			"expecting: '(', '[', '='",
			"expecting: '}'",
			"expecting: '}', 'si', 'tantque', 'ecrire', 'retour', id",
			"expecting: '|', 'alors'",
			"expecting: '|', 'faire'",
			"expecting: ';', '|'",
			"expecting: '}', 'si', 'sinon', 'tantque', 'ecrire', 'retour', id, EOF",
			"expecting: '}', 'si', 'sinon', 'tantque', 'ecrire', 'retour', id",
			"expecting: '='",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 5, 6, 7, 2, 3, 8, 9, 10, 11, 12, 13, 2, 5, 14, 15, 12, 16, 7, 17, 18, 19, 20, 21, 15, 15, 15, 15, 15, 22, 10, 5, 23, 15, 22, 24, 12, 12, 12, 12, 12, 12, 12, 12, 12, 25, 15, 15, 26, 22, 27, 19, 20, 21, 21, 15, 15, 15, 15, 28, 12, 22, 15, 15, 29, 3, 26, 12, 12, 7, 12, 30, 31, 32, 22, 33, 34, 12, 35, 24, 11, 12, 36, 31, 32, 28, 28, 23, 32, 22, 14, 35, 31, 37, 32, 4, 4, 38, 32, 28, 32, 32, 32, 12, 32, 35, 32, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
