/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.analysis;

import sc.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAFormProgProgramme(AFormProgProgramme node);
    void caseAListFuncLdf(AListFuncLdf node);
    void caseAEpsLdf(AEpsLdf node);
    void caseADefFuncDf(ADefFuncDf node);
    void caseAOptVarLdvOptional(AOptVarLdvOptional node);
    void caseAEpsLdvOptional(AEpsLdvOptional node);
    void caseALVarLdv(ALVarLdv node);
    void caseAEpsLdv(AEpsLdv node);
    void caseALVarAfterCommaLdvBis(ALVarAfterCommaLdvBis node);
    void caseAEpsLdvBis(AEpsLdvBis node);
    void caseADefVarDv(ADefVarDv node);
    void caseADefVarArrayDv(ADefVarArrayDv node);
    void caseABlocInstructionBi(ABlocInstructionBi node);
    void caseAListInstructionsLi(AListInstructionsLi node);
    void caseAInstructionSuivIBis(AInstructionSuivIBis node);
    void caseAEpsIBis(AEpsIBis node);
    void caseAAffectationI(AAffectationI node);
    void caseAIfI(AIfI node);
    void caseAWhileI(AWhileI node);
    void caseARetI(ARetI node);
    void caseAFunctionCallI(AFunctionCallI node);
    void caseAWriteI(AWriteI node);
    void caseAElseElseBlock(AElseElseBlock node);
    void caseAEpsElseBlock(AEpsElseBlock node);
    void caseAEE(AEE node);
    void caseAAndEE(AAndEE node);
    void caseAAndEAndE(AAndEAndE node);
    void caseACompEAndE(ACompEAndE node);
    void caseAEqualCompE(AEqualCompE node);
    void caseALowerThanCompE(ALowerThanCompE node);
    void caseAArithLowECompE(AArithLowECompE node);
    void caseAPlusArithLowE(APlusArithLowE node);
    void caseAMoinsArithLowE(AMoinsArithLowE node);
    void caseAArithHighEArithLowE(AArithHighEArithLowE node);
    void caseAMultArithHighE(AMultArithHighE node);
    void caseADivArithHighE(ADivArithHighE node);
    void caseANegEArithHighE(ANegEArithHighE node);
    void caseAExclamationMarkNegE(AExclamationMarkNegE node);
    void caseAParenthENegE(AParenthENegE node);
    void caseAParenthesisParenthE(AParenthesisParenthE node);
    void caseAElementParenthE(AElementParenthE node);
    void caseANumberElement(ANumberElement node);
    void caseAFunctionCallElement(AFunctionCallElement node);
    void caseAReadElement(AReadElement node);
    void caseADefFunctionCallAppFunction(ADefFunctionCallAppFunction node);
    void caseAListExpressionLe(AListExpressionLe node);
    void caseAEpsLe(AEpsLe node);
    void caseAExpressionAfterCommaEBis(AExpressionAfterCommaEBis node);
    void caseAEpsEBis(AEpsEBis node);

    void caseTId(TId node);
    void caseTNb(TNb node);
    void caseTPo(TPo node);
    void caseTPf(TPf node);
    void caseTCo(TCo node);
    void caseTCf(TCf node);
    void caseTAo(TAo node);
    void caseTAf(TAf node);
    void caseTComma(TComma node);
    void caseTSemicolon(TSemicolon node);
    void caseTPlus(TPlus node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTNot(TNot node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTEqual(TEqual node);
    void caseTLowerThan(TLowerThan node);
    void caseTInt(TInt node);
    void caseTIf(TIf node);
    void caseTThen(TThen node);
    void caseTElse(TElse node);
    void caseTTq(TTq node);
    void caseTDo(TDo node);
    void caseTLire(TLire node);
    void caseTEcrire(TEcrire node);
    void caseTReturn(TReturn node);
    void caseTEspaces(TEspaces node);
    void caseTCommentaire(TCommentaire node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
