/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.analysis;

import java.util.*;
import sc.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPProgramme().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProgProgramme(AProgProgramme node)
    {
        defaultIn(node);
    }

    public void outAProgProgramme(AProgProgramme node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgProgramme(AProgProgramme node)
    {
        inAProgProgramme(node);
        if(node.getLdvOptional() != null)
        {
            node.getLdvOptional().apply(this);
        }
        if(node.getLdf() != null)
        {
            node.getLdf().apply(this);
        }
        outAProgProgramme(node);
    }

    public void inAListFuncLdf(AListFuncLdf node)
    {
        defaultIn(node);
    }

    public void outAListFuncLdf(AListFuncLdf node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListFuncLdf(AListFuncLdf node)
    {
        inAListFuncLdf(node);
        if(node.getDf() != null)
        {
            node.getDf().apply(this);
        }
        if(node.getLdf() != null)
        {
            node.getLdf().apply(this);
        }
        outAListFuncLdf(node);
    }

    public void inAEpsLdf(AEpsLdf node)
    {
        defaultIn(node);
    }

    public void outAEpsLdf(AEpsLdf node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEpsLdf(AEpsLdf node)
    {
        inAEpsLdf(node);
        outAEpsLdf(node);
    }

    public void inADefFuncDf(ADefFuncDf node)
    {
        defaultIn(node);
    }

    public void outADefFuncDf(ADefFuncDf node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefFuncDf(ADefFuncDf node)
    {
        inADefFuncDf(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPo() != null)
        {
            node.getPo().apply(this);
        }
        if(node.getLdv() != null)
        {
            node.getLdv().apply(this);
        }
        if(node.getPf() != null)
        {
            node.getPf().apply(this);
        }
        if(node.getLdvOptional() != null)
        {
            node.getLdvOptional().apply(this);
        }
        if(node.getBi() != null)
        {
            node.getBi().apply(this);
        }
        outADefFuncDf(node);
    }

    public void inAOptListVarLdvOptional(AOptListVarLdvOptional node)
    {
        defaultIn(node);
    }

    public void outAOptListVarLdvOptional(AOptListVarLdvOptional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOptListVarLdvOptional(AOptListVarLdvOptional node)
    {
        inAOptListVarLdvOptional(node);
        if(node.getLdv() != null)
        {
            node.getLdv().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAOptListVarLdvOptional(node);
    }

    public void inAEpsLdvOptional(AEpsLdvOptional node)
    {
        defaultIn(node);
    }

    public void outAEpsLdvOptional(AEpsLdvOptional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEpsLdvOptional(AEpsLdvOptional node)
    {
        inAEpsLdvOptional(node);
        outAEpsLdvOptional(node);
    }

    public void inAListVarLdv(AListVarLdv node)
    {
        defaultIn(node);
    }

    public void outAListVarLdv(AListVarLdv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListVarLdv(AListVarLdv node)
    {
        inAListVarLdv(node);
        if(node.getDv() != null)
        {
            node.getDv().apply(this);
        }
        if(node.getLdvBis() != null)
        {
            node.getLdvBis().apply(this);
        }
        outAListVarLdv(node);
    }

    public void inAEpsLdv(AEpsLdv node)
    {
        defaultIn(node);
    }

    public void outAEpsLdv(AEpsLdv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEpsLdv(AEpsLdv node)
    {
        inAEpsLdv(node);
        outAEpsLdv(node);
    }

    public void inAListVarAfterCommaLdvBis(AListVarAfterCommaLdvBis node)
    {
        defaultIn(node);
    }

    public void outAListVarAfterCommaLdvBis(AListVarAfterCommaLdvBis node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListVarAfterCommaLdvBis(AListVarAfterCommaLdvBis node)
    {
        inAListVarAfterCommaLdvBis(node);
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getDv() != null)
        {
            node.getDv().apply(this);
        }
        if(node.getLdvBis() != null)
        {
            node.getLdvBis().apply(this);
        }
        outAListVarAfterCommaLdvBis(node);
    }

    public void inAEpsLdvBis(AEpsLdvBis node)
    {
        defaultIn(node);
    }

    public void outAEpsLdvBis(AEpsLdvBis node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEpsLdvBis(AEpsLdvBis node)
    {
        inAEpsLdvBis(node);
        outAEpsLdvBis(node);
    }

    public void inADefVarDv(ADefVarDv node)
    {
        defaultIn(node);
    }

    public void outADefVarDv(ADefVarDv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefVarDv(ADefVarDv node)
    {
        inADefVarDv(node);
        if(node.getVarType() != null)
        {
            node.getVarType().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outADefVarDv(node);
    }

    public void inADefVarArrayDv(ADefVarArrayDv node)
    {
        defaultIn(node);
    }

    public void outADefVarArrayDv(ADefVarArrayDv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefVarArrayDv(ADefVarArrayDv node)
    {
        inADefVarArrayDv(node);
        if(node.getVarType() != null)
        {
            node.getVarType().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getCo() != null)
        {
            node.getCo().apply(this);
        }
        if(node.getNb() != null)
        {
            node.getNb().apply(this);
        }
        if(node.getCf() != null)
        {
            node.getCf().apply(this);
        }
        outADefVarArrayDv(node);
    }

    public void inADefVarAffectationDv(ADefVarAffectationDv node)
    {
        defaultIn(node);
    }

    public void outADefVarAffectationDv(ADefVarAffectationDv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefVarAffectationDv(ADefVarAffectationDv node)
    {
        inADefVarAffectationDv(node);
        if(node.getVarType() != null)
        {
            node.getVarType().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getEqual() != null)
        {
            node.getEqual().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        outADefVarAffectationDv(node);
    }

    public void inABlocInstBi(ABlocInstBi node)
    {
        defaultIn(node);
    }

    public void outABlocInstBi(ABlocInstBi node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocInstBi(ABlocInstBi node)
    {
        inABlocInstBi(node);
        if(node.getAo() != null)
        {
            node.getAo().apply(this);
        }
        if(node.getLi() != null)
        {
            node.getLi().apply(this);
        }
        if(node.getAf() != null)
        {
            node.getAf().apply(this);
        }
        outABlocInstBi(node);
    }

    public void inAListInstLi(AListInstLi node)
    {
        defaultIn(node);
    }

    public void outAListInstLi(AListInstLi node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListInstLi(AListInstLi node)
    {
        inAListInstLi(node);
        if(node.getI() != null)
        {
            node.getI().apply(this);
        }
        if(node.getIBis() != null)
        {
            node.getIBis().apply(this);
        }
        outAListInstLi(node);
    }

    public void inAListInstNextIBis(AListInstNextIBis node)
    {
        defaultIn(node);
    }

    public void outAListInstNextIBis(AListInstNextIBis node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListInstNextIBis(AListInstNextIBis node)
    {
        inAListInstNextIBis(node);
        if(node.getI() != null)
        {
            node.getI().apply(this);
        }
        if(node.getIBis() != null)
        {
            node.getIBis().apply(this);
        }
        outAListInstNextIBis(node);
    }

    public void inAEpsIBis(AEpsIBis node)
    {
        defaultIn(node);
    }

    public void outAEpsIBis(AEpsIBis node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEpsIBis(AEpsIBis node)
    {
        inAEpsIBis(node);
        outAEpsIBis(node);
    }

    public void inAAffectI(AAffectI node)
    {
        defaultIn(node);
    }

    public void outAAffectI(AAffectI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAffectI(AAffectI node)
    {
        inAAffectI(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getEqual() != null)
        {
            node.getEqual().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAAffectI(node);
    }

    public void inAAffectInArrayI(AAffectInArrayI node)
    {
        defaultIn(node);
    }

    public void outAAffectInArrayI(AAffectInArrayI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAffectInArrayI(AAffectInArrayI node)
    {
        inAAffectInArrayI(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getCo() != null)
        {
            node.getCo().apply(this);
        }
        if(node.getNb() != null)
        {
            node.getNb().apply(this);
        }
        if(node.getCf() != null)
        {
            node.getCf().apply(this);
        }
        if(node.getEqual() != null)
        {
            node.getEqual().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAAffectInArrayI(node);
    }

    public void inAIfI(AIfI node)
    {
        defaultIn(node);
    }

    public void outAIfI(AIfI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfI(AIfI node)
    {
        inAIfI(node);
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getThen() != null)
        {
            node.getThen().apply(this);
        }
        if(node.getBi() != null)
        {
            node.getBi().apply(this);
        }
        if(node.getElseBlock() != null)
        {
            node.getElseBlock().apply(this);
        }
        outAIfI(node);
    }

    public void inAWhileI(AWhileI node)
    {
        defaultIn(node);
    }

    public void outAWhileI(AWhileI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileI(AWhileI node)
    {
        inAWhileI(node);
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getBi() != null)
        {
            node.getBi().apply(this);
        }
        outAWhileI(node);
    }

    public void inARetI(ARetI node)
    {
        defaultIn(node);
    }

    public void outARetI(ARetI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARetI(ARetI node)
    {
        inARetI(node);
        if(node.getReturn() != null)
        {
            node.getReturn().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outARetI(node);
    }

    public void inAFuncCallI(AFuncCallI node)
    {
        defaultIn(node);
    }

    public void outAFuncCallI(AFuncCallI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncCallI(AFuncCallI node)
    {
        inAFuncCallI(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPo() != null)
        {
            node.getPo().apply(this);
        }
        if(node.getLe() != null)
        {
            node.getLe().apply(this);
        }
        if(node.getPf() != null)
        {
            node.getPf().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAFuncCallI(node);
    }

    public void inAWriteI(AWriteI node)
    {
        defaultIn(node);
    }

    public void outAWriteI(AWriteI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWriteI(AWriteI node)
    {
        inAWriteI(node);
        if(node.getWrite() != null)
        {
            node.getWrite().apply(this);
        }
        if(node.getPo() != null)
        {
            node.getPo().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getPf() != null)
        {
            node.getPf().apply(this);
        }
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outAWriteI(node);
    }

    public void inAElseElseBlock(AElseElseBlock node)
    {
        defaultIn(node);
    }

    public void outAElseElseBlock(AElseElseBlock node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseElseBlock(AElseElseBlock node)
    {
        inAElseElseBlock(node);
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getBi() != null)
        {
            node.getBi().apply(this);
        }
        outAElseElseBlock(node);
    }

    public void inAEpsElseBlock(AEpsElseBlock node)
    {
        defaultIn(node);
    }

    public void outAEpsElseBlock(AEpsElseBlock node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEpsElseBlock(AEpsElseBlock node)
    {
        inAEpsElseBlock(node);
        outAEpsElseBlock(node);
    }

    public void inAEE(AEE node)
    {
        defaultIn(node);
    }

    public void outAEE(AEE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEE(AEE node)
    {
        inAEE(node);
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getAndE() != null)
        {
            node.getAndE().apply(this);
        }
        outAEE(node);
    }

    public void inAAndEE(AAndEE node)
    {
        defaultIn(node);
    }

    public void outAAndEE(AAndEE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndEE(AAndEE node)
    {
        inAAndEE(node);
        if(node.getAndE() != null)
        {
            node.getAndE().apply(this);
        }
        outAAndEE(node);
    }

    public void inAAndEAndE(AAndEAndE node)
    {
        defaultIn(node);
    }

    public void outAAndEAndE(AAndEAndE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndEAndE(AAndEAndE node)
    {
        inAAndEAndE(node);
        if(node.getAndE() != null)
        {
            node.getAndE().apply(this);
        }
        if(node.getAnd() != null)
        {
            node.getAnd().apply(this);
        }
        if(node.getCompE() != null)
        {
            node.getCompE().apply(this);
        }
        outAAndEAndE(node);
    }

    public void inACompEAndE(ACompEAndE node)
    {
        defaultIn(node);
    }

    public void outACompEAndE(ACompEAndE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACompEAndE(ACompEAndE node)
    {
        inACompEAndE(node);
        if(node.getCompE() != null)
        {
            node.getCompE().apply(this);
        }
        outACompEAndE(node);
    }

    public void inAEqualCompE(AEqualCompE node)
    {
        defaultIn(node);
    }

    public void outAEqualCompE(AEqualCompE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEqualCompE(AEqualCompE node)
    {
        inAEqualCompE(node);
        if(node.getCompE() != null)
        {
            node.getCompE().apply(this);
        }
        if(node.getEqual() != null)
        {
            node.getEqual().apply(this);
        }
        if(node.getArithLowE() != null)
        {
            node.getArithLowE().apply(this);
        }
        outAEqualCompE(node);
    }

    public void inALowerThanCompE(ALowerThanCompE node)
    {
        defaultIn(node);
    }

    public void outALowerThanCompE(ALowerThanCompE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALowerThanCompE(ALowerThanCompE node)
    {
        inALowerThanCompE(node);
        if(node.getCompE() != null)
        {
            node.getCompE().apply(this);
        }
        if(node.getLowerThan() != null)
        {
            node.getLowerThan().apply(this);
        }
        if(node.getArithLowE() != null)
        {
            node.getArithLowE().apply(this);
        }
        outALowerThanCompE(node);
    }

    public void inAArithLowECompE(AArithLowECompE node)
    {
        defaultIn(node);
    }

    public void outAArithLowECompE(AArithLowECompE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArithLowECompE(AArithLowECompE node)
    {
        inAArithLowECompE(node);
        if(node.getArithLowE() != null)
        {
            node.getArithLowE().apply(this);
        }
        outAArithLowECompE(node);
    }

    public void inAPlusArithLowE(APlusArithLowE node)
    {
        defaultIn(node);
    }

    public void outAPlusArithLowE(APlusArithLowE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusArithLowE(APlusArithLowE node)
    {
        inAPlusArithLowE(node);
        if(node.getArithLowE() != null)
        {
            node.getArithLowE().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        if(node.getArithHighE() != null)
        {
            node.getArithHighE().apply(this);
        }
        outAPlusArithLowE(node);
    }

    public void inAMoinsArithLowE(AMoinsArithLowE node)
    {
        defaultIn(node);
    }

    public void outAMoinsArithLowE(AMoinsArithLowE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMoinsArithLowE(AMoinsArithLowE node)
    {
        inAMoinsArithLowE(node);
        if(node.getArithLowE() != null)
        {
            node.getArithLowE().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        if(node.getArithHighE() != null)
        {
            node.getArithHighE().apply(this);
        }
        outAMoinsArithLowE(node);
    }

    public void inAArithHighEArithLowE(AArithHighEArithLowE node)
    {
        defaultIn(node);
    }

    public void outAArithHighEArithLowE(AArithHighEArithLowE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArithHighEArithLowE(AArithHighEArithLowE node)
    {
        inAArithHighEArithLowE(node);
        if(node.getArithHighE() != null)
        {
            node.getArithHighE().apply(this);
        }
        outAArithHighEArithLowE(node);
    }

    public void inAMultArithHighE(AMultArithHighE node)
    {
        defaultIn(node);
    }

    public void outAMultArithHighE(AMultArithHighE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultArithHighE(AMultArithHighE node)
    {
        inAMultArithHighE(node);
        if(node.getArithHighE() != null)
        {
            node.getArithHighE().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getNegE() != null)
        {
            node.getNegE().apply(this);
        }
        outAMultArithHighE(node);
    }

    public void inADivArithHighE(ADivArithHighE node)
    {
        defaultIn(node);
    }

    public void outADivArithHighE(ADivArithHighE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivArithHighE(ADivArithHighE node)
    {
        inADivArithHighE(node);
        if(node.getArithHighE() != null)
        {
            node.getArithHighE().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getNegE() != null)
        {
            node.getNegE().apply(this);
        }
        outADivArithHighE(node);
    }

    public void inANegEArithHighE(ANegEArithHighE node)
    {
        defaultIn(node);
    }

    public void outANegEArithHighE(ANegEArithHighE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegEArithHighE(ANegEArithHighE node)
    {
        inANegEArithHighE(node);
        if(node.getNegE() != null)
        {
            node.getNegE().apply(this);
        }
        outANegEArithHighE(node);
    }

    public void inANotNegE(ANotNegE node)
    {
        defaultIn(node);
    }

    public void outANotNegE(ANotNegE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotNegE(ANotNegE node)
    {
        inANotNegE(node);
        if(node.getNot() != null)
        {
            node.getNot().apply(this);
        }
        if(node.getParenthE() != null)
        {
            node.getParenthE().apply(this);
        }
        outANotNegE(node);
    }

    public void inAParenthENegE(AParenthENegE node)
    {
        defaultIn(node);
    }

    public void outAParenthENegE(AParenthENegE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParenthENegE(AParenthENegE node)
    {
        inAParenthENegE(node);
        if(node.getParenthE() != null)
        {
            node.getParenthE().apply(this);
        }
        outAParenthENegE(node);
    }

    public void inAParenthParenthE(AParenthParenthE node)
    {
        defaultIn(node);
    }

    public void outAParenthParenthE(AParenthParenthE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParenthParenthE(AParenthParenthE node)
    {
        inAParenthParenthE(node);
        if(node.getPo() != null)
        {
            node.getPo().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getPf() != null)
        {
            node.getPf().apply(this);
        }
        outAParenthParenthE(node);
    }

    public void inAElementParenthE(AElementParenthE node)
    {
        defaultIn(node);
    }

    public void outAElementParenthE(AElementParenthE node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElementParenthE(AElementParenthE node)
    {
        inAElementParenthE(node);
        if(node.getElement() != null)
        {
            node.getElement().apply(this);
        }
        outAElementParenthE(node);
    }

    public void inANumberElement(ANumberElement node)
    {
        defaultIn(node);
    }

    public void outANumberElement(ANumberElement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberElement(ANumberElement node)
    {
        inANumberElement(node);
        if(node.getNb() != null)
        {
            node.getNb().apply(this);
        }
        outANumberElement(node);
    }

    public void inAVariableElement(AVariableElement node)
    {
        defaultIn(node);
    }

    public void outAVariableElement(AVariableElement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariableElement(AVariableElement node)
    {
        inAVariableElement(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAVariableElement(node);
    }

    public void inAArrayElementElement(AArrayElementElement node)
    {
        defaultIn(node);
    }

    public void outAArrayElementElement(AArrayElementElement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayElementElement(AArrayElementElement node)
    {
        inAArrayElementElement(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getCo() != null)
        {
            node.getCo().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getCf() != null)
        {
            node.getCf().apply(this);
        }
        outAArrayElementElement(node);
    }

    public void inAReadElement(AReadElement node)
    {
        defaultIn(node);
    }

    public void outAReadElement(AReadElement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReadElement(AReadElement node)
    {
        inAReadElement(node);
        if(node.getRead() != null)
        {
            node.getRead().apply(this);
        }
        if(node.getPo() != null)
        {
            node.getPo().apply(this);
        }
        if(node.getPf() != null)
        {
            node.getPf().apply(this);
        }
        outAReadElement(node);
    }

    public void inAFuncCallElement(AFuncCallElement node)
    {
        defaultIn(node);
    }

    public void outAFuncCallElement(AFuncCallElement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncCallElement(AFuncCallElement node)
    {
        inAFuncCallElement(node);
        if(node.getAppFunction() != null)
        {
            node.getAppFunction().apply(this);
        }
        outAFuncCallElement(node);
    }

    public void inADefFuncCallAppFunction(ADefFuncCallAppFunction node)
    {
        defaultIn(node);
    }

    public void outADefFuncCallAppFunction(ADefFuncCallAppFunction node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefFuncCallAppFunction(ADefFuncCallAppFunction node)
    {
        inADefFuncCallAppFunction(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPo() != null)
        {
            node.getPo().apply(this);
        }
        if(node.getLe() != null)
        {
            node.getLe().apply(this);
        }
        if(node.getPf() != null)
        {
            node.getPf().apply(this);
        }
        outADefFuncCallAppFunction(node);
    }

    public void inAListExpLe(AListExpLe node)
    {
        defaultIn(node);
    }

    public void outAListExpLe(AListExpLe node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListExpLe(AListExpLe node)
    {
        inAListExpLe(node);
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getEBis() != null)
        {
            node.getEBis().apply(this);
        }
        outAListExpLe(node);
    }

    public void inAEpsLe(AEpsLe node)
    {
        defaultIn(node);
    }

    public void outAEpsLe(AEpsLe node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEpsLe(AEpsLe node)
    {
        inAEpsLe(node);
        outAEpsLe(node);
    }

    public void inAExpAfterCommaEBis(AExpAfterCommaEBis node)
    {
        defaultIn(node);
    }

    public void outAExpAfterCommaEBis(AExpAfterCommaEBis node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpAfterCommaEBis(AExpAfterCommaEBis node)
    {
        inAExpAfterCommaEBis(node);
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getEBis() != null)
        {
            node.getEBis().apply(this);
        }
        outAExpAfterCommaEBis(node);
    }

    public void inAEpsEBis(AEpsEBis node)
    {
        defaultIn(node);
    }

    public void outAEpsEBis(AEpsEBis node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEpsEBis(AEpsEBis node)
    {
        inAEpsEBis(node);
        outAEpsEBis(node);
    }
}
